### ISSUE TITLE
Unable to craft with IM

### ISSUE THREAD

**Issue by ABAxStorm** [ImagicalMine/ImagicalMine#231467]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
I am unable to craft with using ImagicalMine. You can get wood, a crafting table, anything and still not be able to craft. I've tried restarting the server and things already and it won't change.

## Reproducing the issue
Getting wooden blocks in survival while running ImagicalMine and trying to craft.

## Client information
Android 5.1, PHP7 and IM 14.2

 
## Optional information
![screenshot_2016-04-29-17-03-06 1](https://cloud.githubusercontent.com/assets/18360816/14932572/684dcc96-0e2d-11e6-99a2-ea48fac9947e.png)
![screenshot_2016-04-29-17-03-11 1](https://cloud.githubusercontent.com/assets/18360816/14932574/7234cbec-0e2d-11e6-97c8-0aea582caf92.png)
![screenshot_2016-04-29-17-03-40 1](https://cloud.githubusercontent.com/assets/18360816/14932575/7b984862-0e2d-11e6-97b4-ac816939fc6b.png)

**Comment by remotevase** [comment]
It would be quite strange is a creating packet was changed. CRAFTING PACKET! Of all things, they had to choose crafting...

**Comment by BlackShadow1** [comment]
@remotevase I think this is our problem, not packet

**Comment by Riegert** [comment]
Does he have the craftingtablefix.phar installed? My guess it was a crafting packet, just like @remotevase said.

**Comment by keithkfng** [comment]
Really? Somebody said something about an error with the plugin back in 0.14.1...

**Comment by keithkfng** [comment]
If it is true, @matcracker or @BlackShadow1 can you implement it into IM? Then we don't even need the plugin...

**Comment by Riegert** [comment]
I still use it, because my crafting does not work without that plugin.

**Comment by BlackShadow1** [comment]
The problem isn't related to packet, there is already a CraftingEventPacket, and in the .so files there isn't any Crafting Packet. @keithkfng I don't know if it's our problem, I'll check now

**Comment by BlackShadow1** [comment]
Confirmed, can't crafting in 0.14.0 version. Don't know in the other

**Comment by matcracker** [comment]
I don't think it's CraftingPacket issue, it's a code issue.

**Comment by ABAxStorm** [comment]
@reigert I don't have that plugin installed.

**Comment by Riegert** [comment]
Oh, you can download it [here](https://raw.githubusercontent.com/ImagicalMine/ImagicalMine-Windows/master/plugins/CraftingTableFix_v2.0-Alpha.phar)@ABAxStorm. I use it, and it works.

**Comment by ABAxStorm** [comment]
@Riegert Thanks, but it doesn't work. :(

**Comment by Riegert** [comment]
I guess it needs to be something with ImagicalMine. I still use that crafttingtablefix.phar , and I can craft. I guess you need to wait for someone to fix this.

**Comment by keithkfng** [comment]
If it doesn't work, show us the error. Make sure you're using the latest version of IM.

**Comment by vnguyen972** [comment]
I'm running ImagicalMine 1.4Elite for windows and on server start , I see this:

2016-04-29 [22:45:59] warning> Loading plugin 'CraftingTableFix' with incompatible API version (the plugin API is not compatible with ImagicalMine API version 2.0.0)

and When I get in the world on survivor mode, I cannot craft anything because, things disappear in the inventory. I can craft the crafting table but then when I put it in my inventory, it disappears when I close my inventory and opens it again.... it happens with everything else I craft too... and things don't show up on the bottom line of the inventory screen...

Please help!!

**Comment by adamruddermann** [comment]
Encountered this same crafting error running MCPE on iOS 0.14.2 on two different hosts running a base ImagicalMine phar.

**Comment by keithkfng** [comment]
@ImagicalMine/developers can somebody hurry up and fix this?

**Comment by remotevase** [comment]
Honestly, I don't know how to

**Comment by Taki21** [comment]
2016-04-29 [22:45:59] warning> Loading plugin 'CraftingTableFix' with incompatible API version (the plugin API is not compatible with ImagicalMine API version 2.0.0)
This is Not an Error,1.14.0 API Plugins still work

**Comment by Taki21** [comment]
@keithkfng Might have a fix for this

**Comment by Taki21** [comment]
Fixed

**Comment by DustyA** [comment]
Still appears to be an issue - there is no option to craft in the latest releases. I can successfully reproduce the problem by following the steps listed by OP.

**Comment by Taki21** [comment]
Ya i noticed...

**Comment by ABAxStorm** [comment]
Works perfect for me now. Maybe try restarting?

**Comment by Taki21** [comment]
it does?!

**Comment by Taki21** [comment]
Did...I actually fix something on ImagicalMine?! What A Miracle...xD

**Comment by DustyA** [comment]
Weird, it's still not working here. I can have logs, but no option to craft when switching to the crafting menu, just "You need to collect blocks to craft!"

**Comment by Taki21** [comment]
Hmm...
