### ISSUE TITLE
Memory leak in #4xx-5xx builds

### ISSUE THREAD

**Issue by robske110** [ImagicalMine/ImagicalMine#592]
```php
Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 130968 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/level/Position.php on line 1203
```
Got that after uprading from #3xx to #4xx Versions! That crash first appeared with /level/ and since then i have given it 8GB instead of 4GB(That was totally fine with #3xx) of ram, should be enough, but it keeps crashing! Weird thingy: the title bar still says 150Mb used so it is not realy registered so its an critical leak! It is always in /level/
//I have given it 16GB now let's see if it will crash again! (I have 24GB of RAM in my system!)

**Comment by thebigsmileXD** [comment]
You must use the cursive one for the code blocks.
And edited the php configuration file? Don't think so

**Comment by robske110** [comment]
What should i edit in the php.ini?
Here is what it is lookig like:
"""php
<will be pasted in here soon!>
"""

**Comment by thebigsmileXD** [comment]
Well.. Read the Documentation!

**Comment by robske110** [comment]
Fatal error: Allowed memory size of 17179869184 bytes exhausted (tried to allocate 130968 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/level/Position.php on line 1203
16GB crashes too (I think you broke the detection of memory lol)
Here is my php.ini finally:
```php
opcache.enable=1
opcache.enable_cli=1
opcache.save_comments=1
opcache.load_comments=1
opcache.fast_shutdown=0
opcache.max_accelerated_files=4096
opcache.interned_strings_buffer=8
opcache.memory_consumption=128
opcache.optimization_level=0xffffffff
date.timezone=CET
short_open_tag=0
asp_tags=0
phar.readonly=0
phar.require_hash=1
```
###But remember: It worked with #3xx builds

**Comment by robske110** [comment]
New Info: It's always in Position.php on Line 1203

**Comment by robske110** [comment]
"Infected" OSes: CentOS, MacOSX (It's most likely with all)
General: Every UNIX system is "infected", probably Windows too!

**Comment by thebigsmileXD** [comment]
After 5 days running still no crashes on Windows, which build again?

**Comment by robske110** [comment]
#410 last confirmation

**Comment by Tolo0** [comment]
I've been having the same crash dump way before I started using 
ImagicalMine. I made some changes to my PocketMine.yml. file and it reduced it from happening. It also only happens when server full.

**Comment by robske110** [comment]
My server is not full

**Comment by thebigsmileXD** [comment]
```

Fatal error: Out of memory (allocated 1481375744) (tried to allocate 337904 bytes) in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/Imagical         Mine-IC_1.0dev#410.phar/src/pocketmine/Server.php on line 1912

Call Stack:
    0.0195     433816   1. {main}() C:\Users\Administrator\Desktop\Server\MinecraftPE\WolvesFortressIM\ImagicalMine-IC_1.0dev#410.phar:0
    0.0224     428704   2. require_once('phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/src/pocketmine/Pocket         Mine.php') C:\Users\Administrator\Desktop\Server\MinecraftPE\WolvesFortressIM\ImagicalMine-IC_1.0dev#410.phar:1
    0.2597     571368   3. pocketmine\Server->__construct() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/sr         c/pocketmine/PocketMine.php:469
   22.9383   31179368   4. pocketmine\Server->start() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/src/pock         etmine/Server.php:1758
   22.9634   31195576   5. pocketmine\Server->tickProcessor() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/         src/pocketmine/Server.php:2157
41052.9593 1476964456   6. pocketmine\Server->tick() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/src/pocke         tmine/Server.php:2279
41053.0140 1477300336   7. pocketmine\Player->checkNetwork() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/s         rc/pocketmine/Server.php:2541
41053.0721 1477820824   8. pocketmine\Server->batchPackets() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/s         rc/pocketmine/Player.php:1679
41053.0743 1478486856   9. zlib_encode() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ImagicalMine-IC_1.0dev#410.phar/src/pocketmine/Server         .php:1912

[07:35:49] [EMERGENCY]: Ein nicht-behebbarer Fehler ist aufgetreten und der Server stürzte ab. Erstelle einen Crash-Dump...
[07:35:49] [EMERGENCY]: Bitte lade die "C:\Users\Administrator\Desktop\Server\MinecraftPE\WolvesFortressIM\CrashDump_Sat_Jan_9-07.35.49-GMT_2016.log" Datei in das Crash         -Archiv hoch und reiche den Link auf der Bug-Reporting Seite ein. Bitte gib so viele Informationen wie möglich.
[07:35:50] [EMERGENCY]: Crashed while crashing, killing process
bin\php\php.exe: Exit 1
```
```

Fatal error: Out of memory (allocated 1624768512) (tried to allocate 131072 bytes) in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/Im         agicalMine-IC_1.0dev#410.phar/src/pocketmine/nbt/NBT.php on line 504

Call Stack:
    0.0216     433896   1. {main}() C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\ImagicalMine-IC_1.0dev#410.phar:0
    0.0253     428856   2. require_once('phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.phar/src/pocketmine/         PocketMine.php') C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\ImagicalMine-IC_1.0dev#410.phar:1
    0.1637     571760   3. pocketmine\Server->__construct() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.p         har/src/pocketmine/PocketMine.php:469
    4.0662   23604144   4. pocketmine\Server->start() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.phar/sr         c/pocketmine/Server.php:1758
    4.1019   23714736   5. pocketmine\Server->tickProcessor() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410         .phar/src/pocketmine/Server.php:2157
19631.1538 1622911128   6. pocketmine\Server->tick() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.phar/src         /pocketmine/Server.php:2279
19631.1542 1622911160   7. pocketmine\Server->checkTickUpdates() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#         410.phar/src/pocketmine/Server.php:2538
19631.1542 1622911192   8. pocketmine\level\Level->doTick() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.p         har/src/pocketmine/Server.php:2380
19631.1543 1622911192   9. pocketmine\level\Level->unloadChunks() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev         #410.phar/src/pocketmine/level/Level.php:823
19631.1543 1622911432  10. pocketmine\level\Level->unloadChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#         410.phar/src/pocketmine/level/Level.php:3107
19631.1547 1622911632  11. pocketmine\level\format\mcregion\McRegion->saveChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/Imagic         alMine-IC_1.0dev#410.phar/src/pocketmine/level/Level.php:2814
19631.1549 1622911632  12. pocketmine\level\format\mcregion\RegionLoader->writeChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/I         magicalMine-IC_1.0dev#410.phar/src/pocketmine/level/format/mcregion/McRegion.php:248
19631.1549 1622911632  13. pocketmine\level\format\mcregion\Chunk->toBinary() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMi         ne-IC_1.0dev#410.phar/src/pocketmine/level/format/mcregion/RegionLoader.php:173
19631.1612 1622907720  14. pocketmine\nbt\NBT->writeCompressed() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#         410.phar/src/pocketmine/level/format/mcregion/Chunk.php:434
19631.2005 1622995520  15. zlib_encode() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#410.phar/src/pocketmine/         nbt/NBT.php:504

[01:39:01] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
```
I haven't even seen that my server is down.. minecraft-pocketserver doesn't send notification mails anymore.

**Comment by thebigsmileXD** [comment]
Also 410

**Comment by robske110** [comment]
Yes, thats the problem and it does not help if you set DO_LOOP=yes because php is not exiting correctly and is not returning to the script

**Comment by thebigsmileXD** [comment]
Anyone can try 407?

**Comment by robske110** [comment]
Will do that this evening

**Comment by thebigsmileXD** [comment]
@robske110 Thanks

**Comment by Tolo0** [comment]
That's my crash dump. Only seems to happen when 50 players online. 

[JkcLhdM4.txt](https://github.com/ImagicalCorp/ImagicalMine/files/83809/JkcLhdM4.txt)

**Comment by Tolo0** [comment]
![screenshot_2016-01-09-19-38-40](https://cloud.githubusercontent.com/assets/13458191/12217974/c4e4bcf2-b708-11e5-95d2-f7dffb5891c7.png)

**Comment by thebigsmileXD** [comment]
$this->NetworkCompressionLevel.. where is it defined?

**Comment by SalmonGER** [comment]
@thebigsmileXD pocketmine.yml line 80?

**Comment by robske110** [comment]
Ok, the crash dumps are not helping! Something filled up the memory critical near and then when it defines a new variable it crashes!

**Comment by robske110** [comment]
And its's random

**Comment by robske110** [comment]
I now have updated my server to the latest build, we'll see if it happens again!

**Comment by thebigsmileXD** [comment]
I'll load 407 and test with that

**Comment by thebigsmileXD** [comment]
No crash

**Comment by KillerXtream** [comment]
407 continue crashing 

Now changed OS to RedHat Linux Enterprise

**Comment by thebigsmileXD** [comment]
Windows, no problems for 3 hours

**Comment by KillerXtream** [comment]
Something is happening..

I'm using it in my cluster
 
Read the RedHatDebugger output please.

**Comment by KillerXtream** [comment]
407 continue crashing:

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in phar:///var/games/mc/servers/fgioujohs/ImagicalMine.phar/src/pocketmine/level/Position.php on line 1203

(Build failed ---> commit: 32e502b -> Using GitPushDEV

Pushed by (6SD1S65GF5CVZ3V132SZ) (User: thebigsmilexd using git -x ci (JenkinsBuild.sh)

Main error: Debugger RHEL7

3616166561 5325432432 532432425
4626256695 5626263216 522632512

Call stack: /sbin/php5 (Dump 5a7c9d5fee12a through HEX)

Call stack (DSI Exception occurred: php --> phar://var/games/McHosting/imagicalmine.phar//src/pocketmine/Server.php

Call stack (DSI Exception occurred: php --> phar://var/games/McHosting/imagicalmine.phar//src/spl/*

Call stack (DSI Exception occurred: php --> phar://var/games/McHosting/imagicalmine.phar//src/pocketmine/Pocketmine.php

Debug information - Sat 17:58 2016 9 Jan - RedHat LinixDebugger ver. 5142a84s

php> Call stack occurred: Out of memory!! (src/pocketmine)
php> Exit code 521ERR

---->Machine information<----

OS: RedHat Enterprise Linux - Datacenter
RAM: 512GB
Available RAM when crash occured: 504.32GB

SSD: DarkCorp Enterprise 1TB (using x50)
Total disk storage: 50TB (50000GB)

Available disk storage: 47.574TB

--OS Info--

Kernel: BlackCore NB by KillerXtream v4.2 ReleaseCORE
Base kernel: Linux 4.2.0-release

Now changed OS to RedHat Linux Enterprise

**Comment by robske110** [comment]
My server runs since yesterday evening stable with build 416! (10Hours)

**Comment by thebigsmileXD** [comment]
407 now crashed:
```Fatal error: Out of memory (allocated 1176502272) (tried to allocate 134217728 bytes) in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php on line 517

Call Stack:
    0.0276     433920   1. {main}() C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\ImagicalMine-IC_1.0dev#407.phar:0
    0.0324     428880   2. require_once('phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/PocketMine.php') C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\ImagicalMine-IC_1.0dev#407.phar:1
    0.2744     571848   3. pocketmine\Server->__construct() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/PocketMine.php:469
    3.8456   23603720   4. pocketmine\Server->start() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/Server.php:1758
    3.8836   23714120   5. pocketmine\Server->tickProcessor() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/Server.php:2157
 8496.1689 1174353968   6. pocketmine\Server->tick() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/Server.php:2279
 8496.1693 1174354000   7. pocketmine\Server->checkTickUpdates() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/Server.php:2538
 8496.1693 1174354032   8. pocketmine\level\Level->doTick() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/Server.php:2380
 8496.5153 1174876936   9. pocketmine\entity\Item->onUpdate() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/Level.php:850
 8496.5157 1174877000  10. pocketmine\entity\Entity->checkObstruction() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/entity/Item.php:126
 8496.5157 1174877192  11. pocketmine\level\Level->getBlockIdAt() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/entity/Entity.php:820
 8496.5157 1174877288  12. pocketmine\level\Level->getChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/Level.php:2179
 8496.5157 1174877336  13. pocketmine\level\Level->loadChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/Level.php:2393
 8496.5158 1174877384  14. pocketmine\level\format\mcregion\McRegion->getChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/Level.php:2723
 8496.5158 1174877432  15. pocketmine\level\format\mcregion\McRegion->loadChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/format/mcregion/McRegion.php:278
 8496.5159 1174877608  16. pocketmine\level\format\mcregion\RegionLoader->readChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/format/mcregion/McRegion.php:218
 8496.5161 1174880168  17. pocketmine\level\format\mcregion\RegionLoader->unserializeChunk() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/format/mcregion/RegionLoader.php:121
 8496.5161 1174880168  18. pocketmine\level\format\mcregion\Chunk::fromBinary() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/format/mcregion/RegionLoader.php:131
 8496.5161 1174880408  19. pocketmine\nbt\NBT->readCompressed() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/level/format/mcregion/Chunk.php:318
 8496.5165 1174976800  20. pocketmine\nbt\NBT->read() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php:478
 8496.5165 1174976800  21. pocketmine\nbt\NBT->readTag() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php:467
 8496.5167 1174976984  22. pocketmine\nbt\tag\Compound->read() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php:550
 8496.5167 1174977032  23. pocketmine\nbt\NBT->readTag() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/tag/Compound.php:92
 8496.5168 1174977216  24. pocketmine\nbt\tag\Compound->read() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php:550
 8496.5179 1174978568  25. pocketmine\nbt\NBT->readTag() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/tag/Compound.php:92
 8496.5181 1174978800  26. pocketmine\nbt\tag\Enum->read() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/NBT.php:546
 8496.6056 1175120952  27. pocketmine\nbt\tag\Compound->read() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/tag/Enum.php:175
 8496.6074 1175124976  28. pocketmine\nbt\NBT->readTag() phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#407.phar/src/pocketmine/nbt/tag/Compound.php:92
```
-.- lets see 406.. yay..

**Comment by robske110** [comment]
416 still no crash... Lowering Max Ram to 8GB now!

**Comment by NML32** [comment]
I'm getting a slightly different memory error on my servers. I'm not sure if it's related to this bug report. 

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2200742 bytes)
File: /src/pocketmine/Server
Line: 1961
Type: E_ERROR

Code:
[1952] 			if($p->isConnected()){
[1953] 				$targets[] = $this->identifiers[spl_object_hash($p)];
[1954] 			}
[1955] 		}
[1956] 
[1957] 		if(!$forceSync and $this->networkCompressionAsync){
[1958] 			$task = new CompressBatchedTask($str, $targets, $this->networkCompressionLevel, $channel);
[1959] 			$this->getScheduler()->scheduleAsyncTask($task);
[1960] 		}else{
[1961] 			$this->broadcastPacketsCallback(zlib_encode($str, ZLIB_ENCODING_DEFLATE, $this->networkCompressionLevel), $targets);
[1962] 		}
[1963] 
[1964] 		Timings::$playerNetworkTimer->stopTiming();
[1965] 	}
[1966] 
[1967] 	public function broadcastPacketsCallback($data, array $identifiers){
[1968] 		$pk = new BatchPacket();
[1969] 		$pk->payload = $data;
[1970] 		$pk->encode();
[1971] 		$pk->isEncoded = true;

**Comment by robske110** [comment]
Nope that is not related to this!
(You can identify this bug: If the php process is still running(no return to the start.sh) its this bug, if not and if you set doloop to yes and it loops then it is not this bug)
Still no sight in 416 will upgrade this evening

**Comment by remotevase** [comment]
I am 95% sure about this answer, because this has been happening to me since I ran PocketMine 0.10---Well, this is actually a feature that is implemented into the coding. When the server is trying to process something, it will allocate bytes. If you leave the server running for too long, it will run out of bytes to use, because each time it allocates bytes, it does not replace them. 
3 simple fixes I would highly reccommend:
   1) Windows- Use task scheduler to close all "minitty.exe" (I think that's the process)

   2) Windows- Use task scheduler to frequently run a powershelI script that will check for a crash dump, and if there is a crash dump, it would close the server with a crash dump, and open a new "start.cmd"

   3) Any OS- Give the server more RAM

**Comment by robske110** [comment]
1->What is minty.exe?
2->You can do that on UNIX too!
3->If you set it to UNLIMITED THIS ISSUE WILL NEVER OCCUR, it's an wrong detection! The OS still says its using about 1GB the title bar says 750MB and suddenly CRASH (It somehow thinks it surpassed the limit->Crash, but does not exit php right)

**Comment by thebigsmileXD** [comment]
mintty is the console programm
Also thats bullshit.

**Comment by robske110** [comment]
What's bullshit? Killing minty or me?

**Comment by robske110** [comment]
And @remotevase The problem of this post is THAT THERE IS NO CRASHDUMP

**Comment by thebigsmileXD** [comment]
The killing of the process. Its not the cause of the leak. You close mintty, and it closes, you don't need the task manager. Also mintty has no load when pm/im crashes

**Comment by dterweij** [comment]
Crashed 10 times in 24 hours (10 crashlogs). All out of memory. It starts itself, I have loop=yes.

Tho, don't think about making/looking for temp fixes.  This needs to be solved. Somewhere in all the commits there is something coded wrong or even right (made this bug because there is another bug that is now triggered). I suggest the developers to start removing/reverting (localy, not commit to  github) 1 day of commits in each batch. Then of the memory problem is gone you have the day of teh commits where it went wrong. Then revert that day one by one and you hit the commit that introduces this memory leak.

Simple, but takes some time to do this.

Good luck.

**Comment by robske110** [comment]
We're already trying to slowly backgrade jenkins builds to see where it comes from!
And you have an completely different issue: You have an crashdump and the server restarts! (Loop)

**Comment by dterweij** [comment]
Yeah I know its time consuming indeed. Just lets wait for you guys. Respect.

I can live with the loop at the moment. Nobody is in the server this week but me :)

**Comment by KillerXtream** [comment]
#416 commit is STABLE.

48 hours with 2 GB RAM

no crash

**Comment by robske110** [comment]
Yes can confirm that ^416 still no crash... Lowering Max Ram to 8GB now!^ said that earlier

**Comment by remotevase** [comment]
@robske110 well, ImagicalMine is 32 bit, so it cannot execute more than 4 GB of RAM. There is no point in giving ImagicalMine 5,6,7,etc. GB of RAM, because ImagicalMine will only use a maximum of 4 GB...

**Comment by NML32** [comment]
I also rolled back to build #416 and so far I haven't crashed from running out of memory.

**Comment by robske110** [comment]
@remotevase The CONSOLE programm in WINDOWS is 32Bit. And yes the php binary is 32bit but as there are async workers the mainhardlimit makes sense!

**Comment by thebigsmileXD** [comment]
Should work now

**Comment by robske110** [comment]
@thebigsmileXD I think you can add "possibly fixed"

**Comment by KillerXtream** [comment]
#416 Build crashed in hour 154 of execution, now, is a loop.

**Comment by robske110** [comment]
Ok, just experienced it again
It is only happening when the server is running over 12h! (AutoServerRestarter would help, but I want to test this so i wont install it now!)
But in 3xx Builds the server ran a week without problems!
So, not sadly fixed! As @KillerXtream said!
(Build 429) will upgrade soon...

**Comment by robske110** [comment]
Again an crash. So annoying.
I will now work on implementing ASR.. (Oh god i have to make it cancel all the mingles and then restart the server to prevent it from crashing!)
Again: PHP DOES NOT EXIT so we can't actually make it restart after the crash!

**Comment by robske110** [comment]
(Possibly) found reason: Only occurs if another php process is running...
## Not confirmed... testing now

**Comment by thebigsmileXD** [comment]
I don't understand why IM still crashes. I have 2 instances (with xdebug enabled) of ClearSky, everything works perfectly. For 5 days.

**Comment by robske110** [comment]
@thebigsmileXD Could you please update the tags again

**Comment by KillerXtream** [comment]
Build 459 crashed at hour 2 of execution.

Possibly i got a fix.

**Comment by robske110** [comment]
@KillerXtream please tell it! We're clueless...

**Comment by robske110** [comment]
Now something REALY REALY weird happened Look at that log:
```
[19:41:24] [INFO]: Josi_11 joined the game

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/raklib/server/Session.php on line 157
[19:41:28] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed [raklib\server\Session]: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes)
[19:41:50] [INFO]: [Info] rBMCPEServer2.0.1ALPHA MCPEV:0.13.1
[19:42:20] [INFO]: [Info] Ihr könnt Grundstücke erstellen! Gebt /ca für mehr Infos ein!
[19:42:50] [INFO]: Frohes neues Jahr! :)
[19:43:20] [INFO]: [Info] Ihr könnt Grundstücke mit /ca erstellen! Gebt /ca für mehr Infos ein!
[19:43:50] [INFO]: [Info] rBMCPEServer2.0.1ALPHA MCPEV:0.13.1
[19:44:20] [INFO]: [Info] Ihr könnt Grundstücke erstellen! Gebt /ca für mehr Infos ein!
[19:44:50] [INFO]: Frohes neues Jahr! :)
[19:45:20] [INFO]: [Info] Ihr könnt Grundstücke mit /ca erstellen! Gebt /ca für mehr Infos ein!
[19:45:50] [INFO]: [Info] rBMCPEServer2.0.1ALPHA MCPEV:0.13.1
[19:46:20] [INFO]: [Info] Ihr könnt Grundstücke erstellen! Gebt /ca für mehr Infos ein!
[19:46:50] [INFO]: Frohes neues Jahr! :)
[19:47:20] [INFO]: [Info] Ihr könnt Grundstücke mit /ca erstellen! Gebt /ca für mehr Infos ein!
[19:47:50] [INFO]: [Info] rBMCPEServer2.0.1ALPHA MCPEV:0.13.1
list
[19:48:06] [INFO]: There are 8/50 players online:
[19:48:06] [INFO]: [User] Chaosflo44, [User] sonic, [User] Mrv, [User] Wolf_girldidi202, [User] Polizist, [User] ThE_bIg_PaNdA, [User] LemelaHD, [User] Josi_11
gc
[19:48:08] [INFO]: ---- Garbage collection result ----
[19:48:08] [INFO]: Chunks: 0
[19:48:08] [INFO]: Entities: 0
[19:48:08] [INFO]: Tiles: -6
[19:48:08] [INFO]: Cycles: 767
[19:48:08] [INFO]: Memory freed: 1 MB
lagg cöe^R
lagg c^R
say Hallo?
[19:48:17] [INFO]: [Server] Hallo?
[19:48:20] [INFO]: [Info] Ihr könnt Grundstücke erstellen! Gebt /ca für mehr Infos ein!
say Ist irgende^R
say Ist irgendjemand da?
[19:48:35] [INFO]: [Server] Ist irgendjemand da?
say LOL, W^R
say LOL, WAS S^R
say LOL, WAS ^R
say LOL, WAS?!
[19:48:43] [INFO]: [Server] LOL, WAS?!
```

**Comment by robske110** [comment]
With CTRL+C on mac i could even bring the main thread to safely shutdown without RakLib:
```
^C[19:52:40] [INFO]: Disabling Alias v1.2.0
[19:52:40] [INFO]: Disabling BanItem v2.1
[19:52:40] [INFO]: Disabling BlockLocations v1.0.2
[19:52:40] [INFO]: Disabling Broadcaster v1.16
[19:52:40] [INFO]: Disabling Cameraman v1.1
[19:52:40] [INFO]: Disabling ClearLagg v1.1.0
[19:52:40] [INFO]: Disabling CustomRanks v1.0.0
[19:52:40] [INFO]: [CustomRanks] Restoring original names...
[19:52:40] [INFO]: Disabling DevTools v1.10.0
[19:52:40] [INFO]: Disabling EasyMOTD v1.0a
[19:52:40] [INFO]: Disabling InvSee v0.0.1
[19:52:40] [INFO]: Disabling iProtector v3.1a
[19:52:40] [INFO]: Disabling BlockSniffer v1.0.0
[19:52:40] [INFO]: Disabling NameCorrector v1.0.0#build010
[19:52:40] [INFO]: Disabling Slapper v1.2.8
[19:52:40] [INFO]: Disabling WorldFixer v1
[19:52:40] [INFO]: Disabling WorldProtect v2.2.0
[19:52:40] [INFO]: Disabling CustomAreas v1.1
[19:52:40] [INFO]: Disabling Lightning v1
[19:52:40] [INFO]: Disabling 1vs1 v0.0.4
[19:52:40] [INFO]: Disabling ServerCore v1.0.2ALPHA-2.3b1
[19:52:40] [INFO]: Disabling SignStatus v3.0.0
[19:52:40] [NOTICE]: [SignStatus] SignStatus disabled
[19:52:40] [INFO]: Disabling SimpleAuth v1.8.1
[19:52:40] [INFO]: Disabling TPA v0.2.2InDev
[19:52:40] [INFO]: Disabling WorldEditor v1.0.3-0.1
[19:52:40] [INFO]: Chaosflo44 left the game
[19:52:40] [INFO]: Chaosflo44[/84.178.254.134:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: sonic left the game
[19:52:40] [INFO]: sonic[/109.193.75.230:61337] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: Mrv left the game
[19:52:40] [INFO]: Mrv[/84.59.3.166:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: Wolf_girldidi202 left the game
[19:52:40] [INFO]: Wolf_girldidi202[/79.197.245.50:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: Polizist left the game
[19:52:40] [INFO]: Polizist[/91.10.200.159:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: ThE_bIg_PaNdA left the game
[19:52:40] [INFO]: ThE_bIg_PaNdA[/87.135.127.108:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: LemelaHD left the game
[19:52:40] [INFO]: LemelaHD[/84.135.81.166:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: Josi_11 left the game
[19:52:40] [INFO]: Josi_11[/87.171.128.86:19132] logged out due to Der Server kommt gleich wieder on!
[19:52:40] [INFO]: Unloading level "world"
[19:52:40] [INFO]: Unloading level "null"
[19:52:40] [INFO]: Unloading level "KPVPL"
```

**Comment by KillerXtream** [comment]
Question: What plugins are you using? And, what is the current build of ImagicalMine?

**Comment by KillerXtream** [comment]
Something is going with plugins, i got ImagicalMine work without plugins

**Comment by thebigsmileXD** [comment]
I got ClearSky and IM working with 68 plugins

**Comment by keithkfng** [comment]
If anybody ever mentions ClearSky again, I'm going to spew. IM will have more devs to take over shortly.

**Comment by robske110** [comment]
Ok, IM @KillerXtream as stated above it began with #4xx Builds! I just upgraded added no plugins... And after a while the server crashed...
The problem is: Now the php process is using 500MB of RAM...

**Comment by thebigsmileXD** [comment]
@keithkfng We fixed IM. Sorry, but we can't merge anymore. Anvils are about to be fixed

**Comment by keithkfng** [comment]
Merge?! Are you kidding me?

**Comment by thebigsmileXD** [comment]
@keithkfng Okay, then not. Should i leave IM?

**Comment by keithkfng** [comment]
I don't want to merge it. I want it REPLACED. LOL

**Comment by robske110** [comment]
Is IM really dead now?

**Comment by thebigsmileXD** [comment]
No.

**Comment by dterweij** [comment]
The memory leak/100% usage is back.
No crash, it freezes now. Only a kill -9 is ending the process.

Using the git pull code from 2 hours ago.

![a](https://cloud.githubusercontent.com/assets/1059028/12361618/856ec1ce-bbbf-11e5-9ff6-dcb10345f2ec.png)
![b](https://cloud.githubusercontent.com/assets/1059028/12361617/8569c16a-bbbf-11e5-976b-57f3245ffe93.png)

**Comment by thebigsmileXD** [comment]
Its ImagicalMine, what you think? Too much magic

**Comment by robske110** [comment]
@dterweij That has nothing to do with this issue!

**Comment by keithkfng** [comment]
Actually I'm getting in touch with HmHmmHm believe it or not...

**Comment by dterweij** [comment]
@robske110 It has.

I let it run and the memory usage goes up and up and up (while a client can not connect anymore)

Then it ends as :
ImagicalMine Crash Dump Sat Jan 16 08:34:23 CET 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes)
File: /src/pocketmine/event/Timings
Line: 209
Type: E_ERROR


So it can run for about 4 hours overhere. Only one time I did connect (Client) and logged out.

**Comment by robske110** [comment]
Again: The ISSUE described in this ISSUE is that there is NO Crashdump
This issue is no memory leak directly as the server runs fine with about 500MB and then php S U D D E N L Y crashes and php does N O T exit... The server does NOT shutdown after this crash as on normal memory crashes!

**Comment by keithkfng** [comment]
@ChalkPE could you try fixing this? Thanks XD

**Comment by robske110** [comment]
We don't have any clue why this happenes so how to fix it already?

**Comment by robske110** [comment]
Sorry

**Comment by robske110** [comment]
Due to: IT DOES NOT START

**Comment by keithkfng** [comment]
Possibly this issue is related to #657...

**Comment by robske110** [comment]
Partly yes: I got one time raklib crashing
But no: Mainly RakLib continues just main thread crashes

**Comment by robske110** [comment]
Testing on 5xx builds now

**Comment by robske110** [comment]
Confirmed to happen on 512.

**Comment by robske110** [comment]
Dawn that button is annyoing
Will test it now after the RakLib fix!

**Comment by icsmoke-mcpe** [comment]
can u give ur pocketmine.yml?

and look at IM #522

**Comment by dterweij** [comment]
Should be solved by #657 looks very good now!

**Comment by keithkfng** [comment]
Thank you to @cr0sh if it really has been solved XD

**Comment by robske110** [comment]
I will wait 24hours, if no server crash i will close this issue!

**Comment by Driesboy** [comment]
fix work good on mac

**Comment by robske110** [comment]
Have mac too lol

**Comment by Driesboy** [comment]
haha

**Comment by robske110** [comment]
Will close in 24h (if my server does not crash!)

**Comment by Driesboy** [comment]
i have read this I will wait 24hours, if no server crash i will close this issue! ^

**Comment by dterweij** [comment]
After 11 hours, no crash, no memory leak. I am realy happy now. Now you can go start implement new  things and fix other bugs :)  I have to say, IM is tha best so far. Thank you all!

**Comment by icsmoke-mcpe** [comment]
lol im using 418 and change some setting at pocketmine.yml. then my server never crashing again with memory problem xD

**Comment by FienixEC** [comment]
would u mind sharing the settings u changed? would greatly appreciate it!

**Comment by Taki21** [comment]
Im trying some settings out...so far no crashes after 8 hours!

**Comment by Taki21** [comment]
WOW! 750 MB reached and still no crash! I think these options im using are working! Ill check for another few Hours!

**Comment by robske110** [comment]
That PR is useless
And anyway this issue is fixed (It was RAKLIB)
If you still have problems with the LATEST ImagicalMine/master jenkins build please report in the next 12hours, if no one reports anything i will close this!

**Comment by robske110** [comment]
Server just crashed
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /Users/Tim/Desktop/Pocket_Server_0.13.x/src/raklib/server/Session.php on line 156

**Comment by Driesboy** [comment]
i dont have that

**Comment by dterweij** [comment]
Still not crashed here. 2 days heavy usage by me and my 3 kids. Tho just 4 users, dont know what happens when there are 100 users doing much...

**Comment by robske110** [comment]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/raklib/server/Session.php on line 156
Again an crash there! Going to look into it...

**Comment by robske110** [comment]
LOL It crashes on unset(STUFF) isn't that freeing up memory?!

**Comment by robske110** [comment]
https://github.com/ImagicalMine/ImagicalMine/blob/master/src/raklib/server/Session.php#L156

**Comment by PocketKiller** [comment]
OMG -_-

**Comment by robske110** [comment]
omg?

**Comment by PocketKiller** [comment]
i am tired of this happening always

**Comment by robske110** [comment]
But how can unset() use more memory? Isn't it desired to free up mem?

**Comment by cr0sh** [comment]
I think PHP tried to allocate tiny space for stack tracing, triggering out-of-memory error.

**Comment by keithkfng** [comment]
Maybe trying setting your debug level to 10 in pocketmine.yml..?

**Comment by thebigsmileXD** [comment]
Above debug level 2 you won't see anything more -.-"

**Comment by keithkfng** [comment]
LOL

**Comment by icsmoke-mcpe** [comment]
Disable all ur memory option on pocketmine.yml (set to 0)

This is work for me, im using IM-418

**Comment by robske110** [comment]
This will hurt your system badly if the server hangs in an loop. (Memory use 100%)
And as I'm having very sensive data on the same machine: No, thanks (I have 24GB of RAM)

**Comment by robske110** [comment]
And it's 90% on aklib/server/Session.php on line 156

**Comment by icsmoke-mcpe** [comment]
I dont have any probelm with my system xP. My server run perfectly with 4 worlds and the tps still at 16-20

**Comment by robske110** [comment]
I said IF the server will hang in an loop, it could make things bad. Anyway this issue should BE resolved :)

**Comment by icsmoke-mcpe** [comment]
LoL, okay. You can look at ClearSky project xD not adv or something -.- just recomend and wait till this issue fixed

**Comment by robske110** [comment]
Just an notice: This issue will be there too...

**Comment by robske110** [comment]
```php
Fatal error: Allowed memory size of 17179869184 bytes exhausted (tried to allocate 130968 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/level/Position.php on line 1202
```
WHAT THAT LINE DOESN'T EVEN EXIST!

**Comment by BlackShadow1** [comment]
I think it's because the Class position extends much class that are extended too

**Comment by thebigsmileXD** [comment]
Actually.. no, CS just freezes xD

**Comment by PocketKiller** [comment]
this is never happening for me, 0 on pocketmine.yml

**Comment by robske110** [comment]
Again, 0 in pocketmine.yml is an temp fix, and that would work. But this is an Workaround and i don't like workarounds

**Comment by icsmoke-mcpe** [comment]
`memory:
 global-limit: 0
 main-limit: 0
 main-hard-limit: 0
 check-rate: 20
 continuous-trigger: true
 continuous-trigger-rate: 30
`

work fine for me, never got crash cause memory issue and im using server restart

**Comment by robske110** [comment]
I'm slowly getting pissed of...
Stop postint set this to 0 and use server restart, i do know that

**Comment by robske110** [comment]
And BTW:
This issue isn't that critical anymore, because PHP exits now, and thefore you can make an loop!

**Comment by HmHmmHm** [comment]
I fixed this problem in php7 branch
please check php7 branch version

**Comment by icsmoke-mcpe** [comment]
okay im leave this issue, i just want help you sorry if not helped

**Comment by robske110** [comment]
Why close?

**Comment by HmHmmHm** [comment]
@robske110 it is fixed php7 branch
and will be merge master&php7

**Comment by robske110** [comment]
Jenkins is still unable to compile the php7 branch.
And I still need php7 lib for pocketmine (MACOSX)

**Comment by keithkfng** [comment]
@HmHmmHm if you happen to merge them together, I’d lik to keep the commits on the master branch because the php7 commits can be re-done later...

**Comment by HmHmmHm** [comment]
@keithkfng yes, now i working on php7->master merge, is it ok?

**Comment by robske110** [comment]
I would wait with that merge until the 0.14 branch is merged...

**Comment by HmHmmHm** [comment]
it will be need time, 0.14 hasn't released yet
but we can start like a php7-0.14 branch

**Comment by robske110** [comment]
yes, like start 1000 branches mess everything up and let github handle it :)
sorry, NO offence

**Comment by robske110** [comment]
THIS IS NOT FIXED!
My server crashes almost every 3 hours!
